# Generated by Django 5.0.1 on 2024-02-10 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_product_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
    ]
