# Generated by Django 5.0.1 on 2024-02-10 14:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.UUID('35ca3fbf-1abb-4de7-a79a-41a30e30618c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
