# Generated by Django 5.0.1 on 2024-02-10 17:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0cc8d235-6a3a-44e2-b417-f8ae36b24e80'), editable=False, primary_key=True, serialize=False),
        ),
    ]
