# Generated by Django 5.0.1 on 2024-02-10 17:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_category_id_product_category'),
        ('order', '0005_remove_order_product_id_alter_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_id',
            field=models.ManyToManyField(to='api.product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4f13a8a4-b55b-4551-9ec4-f29f10dbfb9e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
