# Generated by Django 5.0.1 on 2024-02-10 17:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_product_id_alter_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.UUID('10a19ad9-2ce3-4176-b8db-74b26f857e9b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
